default_language_version:
    python: python3

repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1
    hooks:
      - id: commitizen
        stages: [commit-msg]
        files: '^(pdbstore|tests|installer)/'
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: '^(pdbstore|tests|installer)/'
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: '^(pdbstore|tests|installer)/'
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.1
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest==7.2.2
          - Jinja2
          - pefile
          - colorama
        files: '^(pdbstore|tests|installer)/'
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies:
          - types-setuptools==65.7.0.4
          - Jinja2
          - pefile
          - colorama
        files: '^(pdbstore|tests|installer)/'