codecov:
  notify:
    after_n_builds: 2
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  after_n_builds: 1
  layout: "diff,flags,files"
  behavior: default
  require_changes: false

github_checks:
  annotations: true